version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '1234'
    ports:
    - "27017:27017"
    volumes:
    - local-mongo:/data/db
    command: [ --auth ]

volumes:
  local-mongo:
